// Typed access to the sample passport data generated by the Go scoring
// engine (`make demo-data` → api/cmd/demodata). Do not edit the JSON by
// hand — regenerate it.
import demoJson from "./demo-passport.json";

export interface ScoreComponent {
  key: string;
  weight: number;
  raw: number;
  weighted: number;
}

export interface PassportData {
  sample: boolean;
  generated_by: string;
  as_of: string;
  seller: {
    name: string;
    slug: string;
    location: string;
    member_since: string;
    tagline: string;
    website: string;
  };
  score: {
    score_version: string;
    overall: number;
    grade: string;
    confidence: number;
    components: ScoreComponent[];
    inputs: {
      tenure_years: number;
      effective_events: number;
      orders_12mo_weighted: number;
    };
  };
  stats: {
    orders: number;
    reviews: number;
    avg_rating: number;
    disputes: number;
  };
  sources: {
    platform: string;
    kind: string;
    status: string;
    count: number;
    detail: string;
  }[];
  history: {
    as_of: string; // "2026-07"
    overall: number;
    grade: string;
  }[];
  attestation: {
    kid: string;
    payload: Record<string, unknown>;
    signature_b64: string;
    public_key_jwk: {
      kty: string;
      crv: string;
      x: string;
      kid: string;
      alg: string;
      use: string;
    };
    note: string;
  };
}

export const demoPassport = demoJson as PassportData;

// Buyer-friendly names and explanations for score components.
export const componentLabels: Record<string, { label: string; explain: string }> = {
  rating: {
    label: "Review quality",
    explain: "Weighted average of verified reviews: recent reviews count more, and small samples are discounted.",
  },
  defect: {
    label: "Order reliability",
    explain: "Share of verified orders completed without disputes or cancellations, statistically adjusted for volume.",
  },
  volume: {
    label: "Sales volume",
    explain: "Order volume over the last 12 months.",
  },
  recency: {
    label: "Recent activity",
    explain: "Whether the store is actively selling right now.",
  },
  diversity: {
    label: "Connected storefronts",
    explain: "Number of independently verified storefront connections.",
  },
  tenure: {
    label: "Track record",
    explain: "How many years of history back this passport.",
  },
};
