// Typed access to the worked scoring examples generated by the Go engine
// (`make demo-data` → api/cmd/demodata). Do not edit the JSON by hand.
import examplesJson from "./score-examples.json";
import type { PassportData } from "./demo";

export type ScoreResult = PassportData["score"];

export interface ScoreExample {
  key: string;
  title: string;
  profile: string;
  result: ScoreResult;
  then_as_of?: string;
  then?: ScoreResult;
}

export const scoreExamples = examplesJson as {
  sample: boolean;
  generated_by: string;
  as_of: string;
  examples: ScoreExample[];
};

export function component(r: ScoreResult, key: string) {
  const c = r.components.find((c) => c.key === key);
  if (!c) throw new Error(`missing score component ${key}`);
  return c;
}
