import type { Metadata } from "next";
import Link from "next/link";
import { demoPassport } from "@/lib/demo";
import { scoreExamples, component } from "@/lib/score-examples";
import { ArrowRight } from "@/components/icons";
import { Overline, btnPrimary } from "@/components/ui";

export const metadata: Metadata = {
  title: "How the score works — Reputation Passport",
  description:
    "The full scoring formula: component weights, statistical discounts, the 24-month dispute window, and worked examples computed by the real engine.",
};

// Weights and mechanics below mirror api/internal/score (score v1). The
// worked examples are generated by that engine via `make demo-data`.
const formulaRows: [string, number, string][] = [
  [
    "Review quality",
    40,
    "Recency-weighted Bayesian mean of your ratings. The prior is 25 pseudo-reviews at 3.8/5, so five perfect reviews score around 0.75, not 1.0; review weight halves every 365 days.",
  ],
  [
    "Order reliability",
    25,
    "Wilson 95% lower bound of your non-defect rate over verified orders in the trailing 24 months. Disputes and cancellations stop counting 24 months after they happen.",
  ],
  [
    "Sales volume",
    15,
    "Log-scaled trailing-12-month order count, saturating at 1,000 orders. Doubling a small store helps a lot; a giant store can't buy the score.",
  ],
  [
    "Recent activity",
    10,
    "Half-life decay on days since your last sale (halves every 90 days). Active stores score full marks; dormant ones fade.",
  ],
  [
    "Connected storefronts",
    5,
    "Independently verified storefront connections, capped at 3. One storefront earns a third of this component.",
  ],
  [
    "Track record",
    5,
    "Years since your first recorded event, capped at 5.",
  ],
];

const grades: [string, string][] = [
  ["A+", "90–100"],
  ["A", "80–89"],
  ["B", "65–79"],
  ["C", "50–64"],
  ["D", "below 50"],
];

const linkClass =
  "underline decoration-line-strong underline-offset-[3px] hover:decoration-accent";

export default function ScoreDocsPage() {
  const [newSeller, spike, single] = scoreExamples.examples;
  const p = demoPassport;

  return (
    <main id="main" className="mx-auto w-full max-w-3xl flex-1 px-6 py-14">
      <Overline>Scoring</Overline>
      <h1 className="mt-3 text-4xl font-semibold tracking-[-0.025em]">
        How the score works
      </h1>
      <p className="mt-4 max-w-2xl text-lg leading-[1.65] text-ink-secondary">
        The formula is versioned (currently {p.score.score_version}),
        published in full, and deliberately hard to game. This page states
        every weight and every discount, then shows what real profiles score
        — including the imperfect ones.
      </p>

      <section className="mt-12">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Six components, weights published
        </h2>
        <div className="mt-5">
          {formulaRows.map(([label, weight, body]) => (
            <div
              key={label}
              className="grid gap-2 border-t border-line py-5 sm:grid-cols-[64px_200px_1fr]"
            >
              <span className="font-mono text-sm text-ink-tertiary">
                {weight} pts
              </span>
              <h3 className="text-base font-semibold">{label}</h3>
              <p className="text-sm leading-[1.65] text-ink-secondary">
                {body}
              </p>
            </div>
          ))}
        </div>
        <div className="mt-6 flex flex-wrap items-baseline gap-x-6 gap-y-2 border-t border-line pt-5">
          <Overline>Grades</Overline>
          {grades.map(([g, range]) => (
            <span key={g} className="font-mono text-sm">
              <span className="font-semibold text-brass">{g}</span>{" "}
              <span className="text-ink-tertiary">{range}</span>
            </span>
          ))}
        </div>
        <p className="mt-4 max-w-2xl text-sm leading-[1.65] text-ink-secondary">
          Confidence is reported separately and never blended into the score:
          it grows with the amount of evidence (50 effective events puts it
          at 50%) so anyone reading a passport can see how much history backs
          the number.
        </p>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          What real profiles score
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-[1.65] text-ink-secondary">
          Three fixed sample profiles, each scored by the production engine
          (not marketing numbers; regenerate them any time with the
          published formula). Sample data, clearly labeled.
        </p>

        <div className="mt-6 space-y-5">
          <article className="rounded-md border border-line-strong bg-surface p-6">
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <h3 className="text-base font-semibold">{newSeller.title}</h3>
              <p className="font-mono text-sm">
                <span className="text-xl font-semibold">
                  {newSeller.result.overall.toFixed(1)}
                </span>{" "}
                <span className="font-semibold text-brass">
                  {newSeller.result.grade}
                </span>{" "}
                <span className="text-ink-tertiary">
                  · {Math.floor(newSeller.result.confidence * 100)}% confidence
                </span>
              </p>
            </div>
            <p className="mt-2 text-sm leading-[1.65] text-ink-secondary">
              {newSeller.profile}
            </p>
            <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
              The Bayesian prior is doing its job: 30 reviews averaging 4.9
              earn{" "}
              <span className="font-mono">
                {component(newSeller.result, "rating").weighted.toFixed(1)}/40
              </span>{" "}
              on review quality, not a perfect score, and the confidence
              figure says plainly how much evidence there is. A{" "}
              <span className="font-semibold text-ink">
                {newSeller.result.grade}
              </span>{" "}
              at seven months is a track record worth publishing, not a
              penalty. You see your score privately before deciding to
              publish; nothing is public until you choose.
            </p>
          </article>

          <article className="rounded-md border border-line-strong bg-surface p-6">
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <h3 className="text-base font-semibold">{spike.title}</h3>
              <p className="font-mono text-sm">
                <span className="text-ink-tertiary">
                  {spike.then_as_of}:{" "}
                  {spike.then ? spike.then.overall.toFixed(1) : "–"}{" "}
                  {spike.then?.grade}
                </span>{" "}
                <ArrowRight size={14} className="inline text-ink-tertiary" />{" "}
                <span className="text-xl font-semibold">
                  {spike.result.overall.toFixed(1)}
                </span>{" "}
                <span className="font-semibold text-brass">
                  {spike.result.grade}
                </span>
              </p>
            </div>
            <p className="mt-2 text-sm leading-[1.65] text-ink-secondary">
              {spike.profile}
            </p>
            <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
              While the cluster sat inside the 24-month window, order
              reliability read{" "}
              <span className="font-mono">
                {spike.then
                  ? component(spike.then, "defect").weighted.toFixed(1)
                  : "–"}
                /25
              </span>
              . Today it reads{" "}
              <span className="font-mono">
                {component(spike.result, "defect").weighted.toFixed(1)}/25
              </span>
              : disputes stop counting against you 24 months after they
              happen, by formula rather than by appeal. The grade never
              dropped below A. A bad quarter costs points for two years; it
              does not follow you forever.
            </p>
          </article>

          <article className="rounded-md border border-line-strong bg-surface p-6">
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <h3 className="text-base font-semibold">{single.title}</h3>
              <p className="font-mono text-sm">
                <span className="text-xl font-semibold">
                  {single.result.overall.toFixed(1)}
                </span>{" "}
                <span className="font-semibold text-brass">
                  {single.result.grade}
                </span>{" "}
                <span className="text-ink-tertiary">
                  · {Math.floor(single.result.confidence * 100)}% confidence
                </span>
              </p>
            </div>
            <p className="mt-2 text-sm leading-[1.65] text-ink-secondary">
              {single.profile}
            </p>
            <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
              Being Shopify-only caps exactly one component: connected
              storefronts at{" "}
              <span className="font-mono">
                {component(single.result, "diversity").weighted.toFixed(1)}/5
              </span>
              . That is at most 3.3 points left on the table; every other
              component is fully reachable, and this profile lands{" "}
              <span className="font-mono">
                {single.result.overall.toFixed(1)}
              </span>{" "}
              with one store.
            </p>
          </article>
        </div>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Self-reported data is treated with open suspicion
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-[1.65] text-ink-secondary">
          CSV-imported history is labeled everywhere, carries half weight in
          review quality and volume, contributes nothing to order reliability
          (you can&apos;t prove the absence of disputes from a self-report),
          and a passport with only self-reported history is capped at grade B
          no matter what. Full provenance rules are in{" "}
          <Link href="/docs/verification" className={linkClass}>
            how verification works
          </Link>
          .
        </p>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          The formula is versioned
        </h2>
        <p className="mt-3 max-w-2xl text-sm leading-[1.65] text-ink-secondary">
          Every score snapshot carries its{" "}
          <code className="font-mono">score_version</code>. When the formula
          changes, the version changes; a number never silently means
          something different than it did when it was signed.
        </p>
      </section>

      <section className="mt-14 flex flex-wrap items-center justify-between gap-5 rounded-md border border-line-strong bg-surface p-6 sm:p-8">
        <div>
          <Overline>See it live</Overline>
          <h2 className="mt-2 text-base font-semibold">
            The sample passport runs this exact formula
          </h2>
          <p className="mt-1 text-sm leading-[1.65] text-ink-secondary">
            Component bars, 24-month history, and a signature you can verify
            yourself.
          </p>
        </div>
        <Link href="/p/demo" className={btnPrimary}>
          See the sample passport
        </Link>
      </section>
    </main>
  );
}
