import type { Metadata } from "next";
import Link from "next/link";
import { Overline, btnPrimary } from "@/components/ui";

export const metadata: Metadata = {
  title: "About — Reputation Passport",
  description:
    "Who is building Reputation Passport, why it isn't a blockchain, and what early access actually involves.",
};

const CONTACT = "anthonychenjiaqi@gmail.com";

const linkClass =
  "underline decoration-line-strong underline-offset-[3px] hover:decoration-accent";

export default function AboutPage() {
  return (
    <main id="main" className="mx-auto w-full max-w-2xl flex-1 px-6 py-14">
      <Overline>About</Overline>
      <h1 className="mt-3 text-4xl font-semibold tracking-[-0.025em]">
        Who&apos;s behind this
      </h1>

      <div className="mt-6 space-y-5 leading-[1.65] text-ink-secondary">
        <p>
          I&apos;m Anthony Chen, and I&apos;m building Reputation Passport as
          a solo founder. If you connect a store or query the API, I&apos;m
          the person on the other end.
        </p>
        <p>
          The problem is simple to state: a small seller&apos;s hardest-won
          asset is a years-long record of orders, reviews, and resolved
          problems, and it&apos;s trapped inside whichever platform it
          happened on. Expand to a new marketplace and you start from zero.
          Marketplaces feel the mirror image: every applicant is a blank
          slate they pay to investigate. Both sides lose to the same missing
          piece of infrastructure.
        </p>
        <p>
          A confession that doubles as a design principle: the first
          prototype of this product was a blockchain app. I threw it away.
          What sellers and marketplaces actually need is provenance and
          tamper-evidence, and plain cryptography delivers both: reputation
          data imported read-only from platform APIs, canonicalized, and
          signed with Ed25519, so anyone can verify offline that nothing
          changed since we signed it. No tokens, nothing to buy. The{" "}
          <Link href="/docs/verification" className={linkClass}>
            trust model
          </Link>{" "}
          page documents exactly what those signatures prove and, just as
          important, what they don&apos;t.
        </p>
        <p>
          The product is pre-launch and built in the open: the scoring engine
          and signature scheme are real today (the{" "}
          <Link href="/p/demo" className={linkClass}>
            sample passport
          </Link>{" "}
          is generated by the production engine and carries a checkable
          signature), while the import pipeline is in development. The site
          marks what runs now versus what ships at launch, and I&apos;d
          rather earn trust by being checkable than by being loud.
        </p>
      </div>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          What early access involves
        </h2>
        <ul className="mt-4 space-y-3 text-sm leading-[1.65] text-ink-secondary">
          <li>
            You connect your Shopify store read-only, through the official
            API. I never get the ability to change anything, and buyer data
            is stripped before anything is stored.
          </li>
          <li>
            You see your passport and score privately first. Nothing is
            public unless you decide to publish, and you can disconnect and
            delete at any time.
          </li>
          <li>
            Your feedback shapes the{" "}
            <Link href="/docs/score" className={linkClass}>
              scoring formula
            </Link>{" "}
            and the product while the design-partner group is small, and
            founding sellers keep a badge that says they were first.
          </li>
        </ul>
        <a
          href={`mailto:${CONTACT}?subject=Reputation%20Passport%20early%20access&body=Hi%20Anthony%2C%20I%27d%20like%20to%20join%20the%20early%20access%20list.%0A%0AMy%20store%3A%20`}
          className={`${btnPrimary} mt-6`}
        >
          Email me to join early access
        </a>
        <p className="mt-3 text-[13px] text-ink-tertiary">
          One email, no newsletter. I reply personally.
        </p>
      </section>
    </main>
  );
}
