import type { Metadata } from "next";
import Link from "next/link";
import { demoPassport } from "@/lib/demo";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "API preview — Reputation Passport",
  description:
    "What GET /v1/passports/lookup returns: score, confidence, provenance, and an offline-verifiable signature. Sample response generated by the real scoring engine.",
};

// The sample response is assembled from the same JSON the scoring engine
// generates (make demo-data) — the docs can't drift from the product.
const p = demoPassport;
const lookupResponse = {
  passport: {
    id: "pp_01HZDEMO0000000000000000",
    slug: p.seller.slug,
    display_name: p.seller.name,
    published: true,
    member_since: p.seller.member_since,
    identifiers: [
      { kind: "domain", value: "wildflower-candle.example", verified: true },
    ],
    score: p.score,
    stats: p.stats,
    sources: p.sources.map((s) => ({
      platform: s.platform.toLowerCase().replace(".", ""),
      kind: s.kind,
      trust_level: s.status,
      count: s.count,
    })),
    attestation: {
      kid: p.attestation.kid,
      payload: p.attestation.payload,
      signature_b64: p.attestation.signature_b64,
      // Sample data is signed with the demo key; production responses point
      // at the API origin's JWKS.
      keys_url: `${SITE_URL}/.well-known/demo-jwks.json`,
    },
  },
  sample: true,
};

const noMatchResponse = {
  type: "https://reputationpassport.dev/errors/not-found",
  title: "No passport matches the given identifier",
  status: 404,
  detail:
    "No published passport is linked to domain 'unknown-store.example'. Use the invite flow to ask the seller to connect their storefronts.",
  request_id: "req_01HZX0000000000000000000",
};

const codeBlock =
  "overflow-x-auto rounded-lg bg-neutral-100 p-4 text-xs leading-relaxed dark:bg-neutral-900";

export default function ApiDocsPage() {
  return (
    <main id="main" className="mx-auto w-full max-w-3xl flex-1 px-6 py-14">
      <p className="text-sm font-medium text-emerald-700 dark:text-emerald-400">
        API preview
      </p>
      <h1 className="mt-2 text-4xl font-semibold tracking-tight">
        The reputation API
      </h1>
      <p className="mt-3 text-lg text-neutral-600 dark:text-neutral-400">
        REST, JSON, versioned at <code className="text-base">/v1</code>. The
        API is in development — everything below is the committed contract
        (also as{" "}
        <a href="/openapi.yaml" className="underline">
          OpenAPI YAML
        </a>
        ), and the sample response is generated by the real scoring engine,
        clearly marked <code className="text-base">&quot;sample&quot;: true</code>.
      </p>

      <section className="mt-10">
        <h2 className="text-xl font-semibold">Authentication</h2>
        <pre className={codeBlock}>{`Authorization: Bearer rp_live_9a41c9f2...   # production
Authorization: Bearer rp_test_5b02d8e1...   # sandbox — sample sellers only`}</pre>
        <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
          Keys are scoped and revocable. Test keys only ever see sandbox data
          — fabricated data can never leak into production responses.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-xl font-semibold">Look up a seller</h2>
        <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
          By store domain, by SHA-256 of a lowercased email (raw emails never
          reach us), or by platform seller id. Only identifiers the seller has
          verified (DNS TXT or a matching connected storefront) are matchable.
        </p>
        <pre className={codeBlock}>{`GET /v1/passports/lookup?domain=wildflower-candle.example
GET /v1/passports/lookup?email_sha256=b4c9a2...
GET /v1/passports/lookup?platform=shopify&platform_seller_id=gid://shopify/Shop/1234`}</pre>
        <h3 className="mt-5 text-sm font-medium uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
          200 — match found
        </h3>
        <pre className={codeBlock}>{JSON.stringify(lookupResponse, null, 2)}</pre>
        <h3 className="mt-5 text-sm font-medium uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
          404 — no match (RFC 7807)
        </h3>
        <pre className={codeBlock}>{JSON.stringify(noMatchResponse, null, 2)}</pre>
      </section>

      <section className="mt-10">
        <h2 className="text-xl font-semibold">Reading the response</h2>
        <ul className="mt-3 space-y-2 text-sm text-neutral-700 dark:text-neutral-300">
          <li>
            <strong>score.overall / grade</strong>{" "}— 0–100 and A+…D.
            Component breakdown included so your rules can weight what you
            care about.
          </li>
          <li>
            <strong>score.confidence</strong>{" "}— 0–1, how much evidence backs
            the score (verified events count fully, self-reported at half
            weight). Set your own threshold; we don&apos;t blend it into the
            score.
          </li>
          <li>
            <strong>sources[].trust_level</strong>{" "}— provenance of every
            input: <code>verified_api</code>{" "}(imported read-only from the
            platform&apos;s official API) or <code>csv_self_reported</code>{" "}
            (seller-supplied; discounted 50% and capped at grade B).{" "}
            <Link href="/docs/verification" className="underline">
              Full trust model →
            </Link>
          </li>
          <li>
            <strong>attestation</strong>{" "}— Ed25519 signature over the score,
            stats, and sources. Verify offline against the key set at{" "}
            <code>attestation.keys_url</code>{" "}(production: the API
            origin&apos;s <code>/.well-known/jwks.json</code>); cache
            responses and re-verify without us, forever.
          </li>
          <li>
            <strong>score.score_version</strong>{" "}— the formula version. We
            never silently change what a number means.
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="text-xl font-semibold">Other endpoints</h2>
        <pre className={codeBlock}>{`GET  /v1/passports/{id}                  # canonical read
GET  /v1/passports/{id}/score            # score + inline attestation only
GET  /v1/passports/{id}/attestations     # attestation history
POST /v1/verify                          # server-side verification + revocation check
GET  /.well-known/jwks.json              # verification keys, on the API origin (no auth)`}</pre>
        <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
          Rate limits are per-key with standard headers (
          <code>RateLimit-Limit</code>, <code>RateLimit-Remaining</code>,{" "}
          <code>Retry-After</code>{" "}on 429). Breaking changes never happen
          inside /v1.
        </p>
      </section>

      <section className="mt-12 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-emerald-600/30 bg-emerald-600/5 p-6">
        <div>
          <h2 className="text-lg font-semibold">Want sandbox access first?</h2>
          <p className="mt-1 text-sm text-neutral-600 dark:text-neutral-400">
            Design partners get test keys and a direct line to the founder.
          </p>
        </div>
        <Link
          href="/platforms"
          className="rounded-lg bg-emerald-700 px-5 py-2.5 font-medium text-white hover:bg-emerald-800"
        >
          For marketplaces →
        </Link>
      </section>
    </main>
  );
}
