import type { Metadata } from "next";
import Link from "next/link";
import { demoPassport } from "@/lib/demo";
import { SITE_URL } from "@/lib/site";
import { CodeBlock } from "@/components/code-block";
import { ArrowRight } from "@/components/icons";
import { Overline, btnPrimary } from "@/components/ui";

export const metadata: Metadata = {
  title: "API preview — Reputation Passport",
  description:
    "What GET /v1/passports/lookup returns: score, confidence, provenance, and an offline-verifiable signature. Sample response generated by the real scoring engine.",
};

// The sample response is assembled from the same JSON the scoring engine
// generates (make demo-data) — the docs can't drift from the product.
const p = demoPassport;
const lookupResponse = {
  passport: {
    id: "pp_01HZDEMO0000000000000000",
    slug: p.seller.slug,
    display_name: p.seller.name,
    published: true,
    member_since: p.seller.member_since,
    identifiers: [
      { kind: "domain", value: "wildflower-candle.example", verified: true },
    ],
    score: p.score,
    stats: p.stats,
    sources: p.sources.map((s) => ({
      platform: s.platform.toLowerCase().replace(".", ""),
      kind: s.kind,
      trust_level: s.status,
      count: s.count,
    })),
    attestation: {
      kid: p.attestation.kid,
      // The real payload echoes the full signed score object — elided here.
      // Download the complete attestation from the sample passport page.
      // Kept an object so the sample matches the OpenAPI schema type.
      payload: {
        elided:
          "full signed payload (score, stats, sources) — download attestation.json from the sample passport",
      },
      signature_b64: `${p.attestation.signature_b64.slice(0, 16)}…${p.attestation.signature_b64.slice(-8)}`,
      // Sample data is signed with the demo key; production responses point
      // at the API origin's JWKS.
      keys_url: `${SITE_URL}/.well-known/demo-jwks.json`,
    },
  },
  sample: true,
};

const noMatchResponse = {
  type: "https://reputationpassport.dev/errors/not-found",
  title: "No passport matches the given identifier",
  status: 404,
  detail:
    "No published passport matches this domain. Use the invite flow.",
  request_id: "req_01HZX0000000000000000000",
};

const linkClass =
  "underline decoration-line-strong underline-offset-[3px] hover:decoration-accent";

export default function ApiDocsPage() {
  return (
    <main id="main" className="mx-auto w-full max-w-3xl flex-1 px-6 py-14">
      <Overline>API preview</Overline>
      <h1 className="mt-3 text-4xl font-semibold tracking-[-0.025em]">
        The reputation API
      </h1>
      <p className="mt-4 text-lg leading-[1.65] text-ink-secondary">
        REST, JSON, versioned at <code className="font-mono text-base">/v1</code>.
        The API is in development — everything below is the committed contract
        (also as{" "}
        <a href="/openapi.yaml" className={linkClass}>
          OpenAPI YAML
        </a>
        ), and the sample response is generated by the real scoring engine,
        clearly marked{" "}
        <code className="font-mono text-base">&quot;sample&quot;: true</code>.
      </p>

      <section className="mt-12">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Authentication
        </h2>
        <div className="mt-4">
          <CodeBlock
            label="Authorization header"
            code={`Authorization: Bearer rp_live_9a41c9f2...   # production
Authorization: Bearer rp_test_5b02d8e1...   # sandbox — sample sellers only`}
          />
        </div>
        <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
          Keys are scoped and revocable. Test keys only ever see sandbox data;
          fabricated data can never leak into production responses.
        </p>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Look up a seller
        </h2>
        <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
          By store domain, by SHA-256 of a lowercased email (raw emails never
          reach us), or by platform seller id. Only identifiers the seller has
          verified (DNS TXT or a matching connected storefront) are matchable.
        </p>
        <div className="mt-4 space-y-5">
          <CodeBlock
            label="GET /v1/passports/lookup"
            code={`GET /v1/passports/lookup?domain=wildflower-candle.example
GET /v1/passports/lookup?email_sha256=b4c9a2...
GET /v1/passports/lookup?platform=shopify&platform_seller_id=gid://shopify/Shop/1234`}
          />
          <CodeBlock
            label="200 — match found"
            code={JSON.stringify(lookupResponse, null, 2)}
            copyLabel="Copy"
          />
          <CodeBlock
            label="404 — no match (RFC 7807)"
            code={JSON.stringify(noMatchResponse, null, 2)}
          />
        </div>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Reading the response
        </h2>
        <ul className="mt-4 space-y-3 text-sm leading-[1.65] text-ink-secondary">
          <li>
            <strong className="text-ink">score.overall / grade</strong> — 0–100
            and A+…D. Component breakdown included so your rules can weight
            what you care about.
          </li>
          <li>
            <strong className="text-ink">score.confidence</strong>{" "}— 0–1,
            how
            much evidence backs the score (verified events count fully,
            self-reported at half weight). Set your own threshold; we
            don&apos;t blend it into the score.
          </li>
          <li>
            <strong className="text-ink">sources[].trust_level</strong> —
            provenance of every input:{" "}
            <code className="font-mono">verified_api</code>{" "}(imported
            read-only from the platform&apos;s official API) or{" "}
            <code className="font-mono">csv_self_reported</code>{" "}
            (seller-supplied; discounted 50% and capped at grade B).{" "}
            <Link
              href="/docs/verification"
              className={`inline-flex items-center gap-1 ${linkClass}`}
            >
              Full trust model
              <ArrowRight size={14} />
            </Link>
          </li>
          <li>
            <strong className="text-ink">attestation</strong> — Ed25519
            signature over the score, stats, and sources. Verify offline
            against the key set at{" "}
            <code className="font-mono">attestation.keys_url</code>{" "}
            (production: the API origin&apos;s{" "}
            <code className="font-mono">/.well-known/jwks.json</code>); cache
            responses and re-verify without us, forever.
          </li>
          <li>
            <strong className="text-ink">score.score_version</strong> — the
            formula version. We never silently change what a number means.
          </li>
        </ul>
      </section>

      <section className="mt-12 border-t border-line pt-10">
        <h2 className="text-[22px] font-semibold tracking-[-0.01em]">
          Other endpoints
        </h2>
        <div className="mt-4">
          <CodeBlock
            label="Endpoints"
            code={`GET  /v1/passports/{id}                  # canonical read
GET  /v1/passports/{id}/score            # score + inline attestation only
GET  /v1/passports/{id}/attestations     # attestation history
POST /v1/verify                          # server-side verification + revocation check
GET  /.well-known/jwks.json              # verification keys, on the API origin (no auth)`}
          />
        </div>
        <p className="mt-3 text-sm leading-[1.65] text-ink-secondary">
          Rate limits are per-key with standard headers (
          <code className="font-mono">RateLimit-Limit</code>,{" "}
          <code className="font-mono">RateLimit-Remaining</code>,{" "}
          <code className="font-mono">Retry-After</code> on 429). Breaking
          changes never happen inside /v1.
        </p>
      </section>

      <section className="mt-14 flex flex-wrap items-center justify-between gap-5 rounded-md border border-line-strong bg-surface p-6 sm:p-8">
        <div>
          <Overline>Sandbox</Overline>
          <h2 className="mt-2 text-base font-semibold">
            Want sandbox access first?
          </h2>
          <p className="mt-1 text-sm leading-[1.65] text-ink-secondary">
            Design partners get test keys and a direct line to the founder.
          </p>
        </div>
        <Link href="/platforms" className={btnPrimary}>
          For marketplaces
        </Link>
      </section>
    </main>
  );
}
